export const projects = [
  {
    id: "1",
    title: "Confeitaria",
    category: "Branding",
    categoryId: "branding",
    image: "/jana.svg?height=100&width=100",
    gallery: [
      "/adesivo.png?height=400&width=600",
      "/box.png?height=100&width=100",
      "/cartao.jpeg?height=400&width=600",
      "/outdoor.png?height=400&width=600",
    ],
    expertise: ["Pesquisa de usuários", "Design de interface", "Prototipagem", "Testes de usabilidade"],
    client: "FinTech Solutions",
    services: ["UX Research", "UI Design", "Prototyping", "User Testing"],
    featured: true,
  },
  {
    id: "2",
    title: "Identidade Visual para Crypt",
    category: "UI/UX Design",
    categoryId: "ui-ux",
    image: "/crypto2.svg?height=600&width=800",
    gallery: [
      "/crypto.svg?height=400&width=600",
      "/crypto2.svg?height=400&width=600",
      "/crypto3.svg?height=400&width=600",
      "/crypto4.svg?height=400&width=600",
    ],
    expertise: ["Identidade visual", "Design de logotipo", "Materiais impressos", "Embalagens"],
    services: ["Logo Design", "Brand Identity", "Packaging", "Print Materials"],
    featured: true,
  },
  {
    id: "3",
    title: "Inova Frota",
    category: "UI/UX Design",
    categoryId: "ui-ux",
    image: "/frota1.png?height=600&width=800",
    gallery: [
      "/frota2.png?height=400&width=600",
      "/frota3.png?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
    expertise: ["Design de interface", "Visualização de dados", "UX Research", "Prototipagem"],
    client: "Data Analytics Corp",
    services: ["UX Research", "UI Design", "Data Visualization", "Prototyping"],
  },
    {
    id: "4",
    title: "Uber",
    category: "UI/UX Design",
    categoryId: "ui-ux",
    image: "/5.svg?height=600&width=800",
    gallery: [
      "/5.svg?height=400&width=600",
      "/6.svg?height=400&width=600",
      "/7.svg?height=400&width=600",
      "/8.svg?height=400&width=600",
    ],
    expertise: ["Design de interface", "Design responsivo", "Arquitetura da informação", "Prototipagem"],
    client: "Creative Agency",
    services: ["Web Design", "Responsive Design", "Prototyping", "Development"],
    featured: true,
  },
    {
    id: "5",
    title: "Engenheiro",
    category: "Branding",
    categoryId: "branding",
    image: "/eng.jpeg?height=600&width=800",
    gallery: [
      "/alonso.svg?height=400&width=600",
      "/alonso3.png?height=400&width=600",
      "/book.png?height=400&width=600",
      "/alonso2.png?height=400&width=600",
    ],
    expertise: ["Design de interface", "Arquitetura da informação", "Prototipagem", "Testes com usuários"],
    client: "Fashion Brand",
    services: ["UI Design", "UX Research", "Prototyping", "User Testing"],
  },
    {
    id: "6",
    title: "Catálogo de Produtos",
    category: "Design Gráfico",
    categoryId: "graphic-design",
    image: "/1.svg?height=600&width=800",
    gallery: [
      "/test.svg?height=400&width=600",
      "/teste1.svg?height=400&width=600",
      "/teste2.svg?height=400&width=600",
      "/teste3.svg?height=400&width=600",
    ],
    expertise: ["Design editorial", "Direção de fotografia", "Layout", "Produção gráfica"],
    client: "Retail Company",
    services: ["Editorial Design", "Photography Direction", "Layout Design", "Print Production"],
  },

//   {
//     id: "7",
//     title: "Design de Marca",
//     category: "Branding",
//     categoryId: "branding",
//     image: "/placeholder.svg?height=600&width=800",
//     gallery: [
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//     ],
//     expertise: ["Estratégia de marca", "Design de logotipo", "Guia de estilo", "Aplicações da marca"],
//     client: "Tech Startup",
//     services: ["Brand Strategy", "Logo Design", "Visual Identity", "Brand Guidelines"],
//   },
//   {
//     id: "8",
//     title: "Aplicativo de Delivery",
//     category: "UI/UX Design",
//     categoryId: "ui-ux",
//     image: "/placeholder.svg?height=600&width=800",
//     gallery: [
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//     ],
//     expertise: ["Design de interface", "Design de interação", "Prototipagem", "Testes de usabilidade"],
//     client: "Food Delivery Service",
//     services: ["UX Research", "UI Design", "Interaction Design", "Prototyping"],
//   },
//  {
//     id: "9",
//     title: "Ilustração para Campanha",
//     category: "Ilustração",
//     categoryId: "illustration",
//     image: "/placeholder.svg?height=600&width=800",
//     gallery: [
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//     ],
//     expertise: ["Ilustração digital", "Design de personagens", "Arte conceitual", "Storyboard"],
//     client: "ONG Ambiental",
//     services: ["Digital Illustration", "Character Design", "Campaign Assets"],
//   },
//   {
//     id: "10",
//     title: "Campanha de Marketing Digital",
//     category: "Design Gráfico",
//     categoryId: "graphic-design",
//     image: "/placeholder.svg?height=600&width=800",
//     gallery: [
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//     ],
//     expertise: ["Design para redes sociais", "Banners", "Templates de email", "Animação"],
//     client: "E-commerce Platform",
//     services: ["Social Media Graphics", "Banner Design", "Email Templates", "Animation"],
//   },
//   {
//     id: "11",
//     title: "Website para Estúdio de Arquitetura",
//     category: "Web Design",
//     categoryId: "web-design",
//     image: "/placeholder.svg?height=600&width=800",
//     gallery: [
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//     ],
//     expertise: ["Design de interface", "Design responsivo", "Elementos interativos", "Arquitetura da informação"],
//     client: "Architecture Studio",
//     services: ["Web Design", "Responsive Design", "Interactive Elements", "CMS Setup"],
//   },
//   {
//     id: "12",
//     title: "Ilustrações para Livro Infantil",
//     category: "Ilustração",
//     categoryId: "illustration",
//     image: "/placeholder.svg?height=600&width=800",
//     gallery: [
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//       "/placeholder.svg?height=400&width=600",
//     ],
//     expertise: ["Design de personagens", "Ilustração de cenas", "Design de capa", "Layout"],
//     client: "Publishing House",
//     services: ["Character Design", "Scene Illustration", "Cover Design", "Layout"],
//   },
]
