export const projects = [
  {
    id: "1",
    title: "Confeitaria",
    category: "Branding",
    categoryId: "branding",
    image: "/jana.svg?height=100&width=100",
    gallery: [
      "/adesivo.png?height=400&width=600",
      "/box.png?height=100&width=100",
      "/cartao.jpeg?height=400&width=600",
      "/outdoor.png?height=400&width=600",
    ],
    expertise: ["Identidade visual", "Design de logotipo", "Materiais impressos", "Embalagens"],
    services: ["Logo Design", "Brand Identity", "Packaging", "Print Materials"],
    featured: true,
  },
  {
    id: "2",
    title: "Identidade Visual para Crypt",
    category: "UI/UX Design",
    categoryId: "ui-ux",
    image: "/crypto2.svg?height=600&width=800",
    gallery: [
      "/crypto.svg?height=400&width=600",
      "/crypto2.svg?height=400&width=600",
      "/crypto3.svg?height=400&width=600",
      "/crypto4.svg?height=400&width=600",
    ],
    expertise: ["Design de interface", "Visualização de dados", "UX Research", "Prototipagem"],
    services: ["UX Research", "UI Design", "Data Visualization", "Prototyping"],
    featured: true,
  },
  {
    id: "3",
    title: "Inova Frota",
    category: "UI/UX Design",
    categoryId: "ui-ux",
    image: "/frota1.png?height=600&width=800",
    gallery: [
      "/frota2.png?height=400&width=600",
      "/frota4.png?height=400&width=600",
      "/frota5.png?height=400&width=600",
      "/frota3.png?height=400&width=600",
    ],
    expertise: ["Design de interface", "Visualização de dados", "UX Research", "Prototipagem"],
    services: ["UX Research", "UI Design", "Data Visualization", "Prototyping"],
  },
    {
    id: "4",
    title: "Uber",
    category: "UI/UX Design",
    categoryId: "ui-ux",
    image: "/5.svg?height=600&width=800",
    gallery: [
      "/5.svg?height=400&width=600",
      "/6.svg?height=400&width=600",
      "/7.svg?height=400&width=600",
      "/8.svg?height=400&width=600",
    ],
    expertise: ["Design de interface", "Visualização de dados", "UX Research", "Prototipagem"],
    services: ["UX Research", "UI Design", "Data Visualization", "Prototyping"],
    featured: true,
  },
    {
    id: "5",
    title: "Engenheiro",
    category: "Branding",
    categoryId: "branding",
    image: "/eng.jpeg?height=600&width=800",
    gallery: [
      "/alonso.svg?height=400&width=600",
      "/alonso3.png?height=400&width=600",
      "/book.png?height=400&width=600",
      "/alonso2.png?height=400&width=600",
    ],
    expertise: ["Identidade visual", "Design de logotipo", "Materiais impressos", "Embalagens"],
    services: ["Logo Design", "Brand Identity", "Packaging", "Print Materials"],
  },
    {
    id: "6",
    title: "Catálogo de Produtos",
    category: "Design Gráfico",
    categoryId: "graphic-design",
    image: "/1.svg?height=600&width=800",
    gallery: [
      "/test.svg?height=400&width=600",
      "/teste1.svg?height=400&width=600",
      "/teste2.svg?height=400&width=600",
      "/teste3.svg?height=400&width=600",
    ],
    expertise: ["Design editorial", "Direção de fotografia", "Layout", "Produção gráfica"],
    services: ["Editorial Design", "Photography Direction", "Layout Design", "Print Production"],
  },

  {
    id: "7",
    title: "Design de Marca",
     category: "Web Design",
    categoryId: "web-design",
    image: "/web3.jpeg?height=600&width=800",
    gallery: [
      "/web.png?height=400&width=600",
      "/web3.jpeg?height=400&width=600",
      "/web1.png?height=400&width=600",
      "/web2.png?height=400&width=600",

    ],
    expertise: ["Design de interface", "Design responsivo", "Arquitetura da informação", "Prototipagem"],
    services: ["Web Design", "Responsive Design", "Prototyping", "Development"],
  },
  {
    id: "8",
    title: "Aplicativo Sleep Sounds",
    category: "UI/UX Design",
    categoryId: "ui-ux",
    image: "/11.svg?height=600&width=800",
    gallery: [
      "/10.svg?height=400&width=600",
      "/9.svg?height=400&width=600",
      "/11.svg?height=400&width=600",
      "/12.png?height=400&width=600",
    ],
    expertise: ["Design de interface", "Visualização de dados", "UX Research", "Prototipagem"],
    services: ["UX Research", "UI Design", "Data Visualization", "Prototyping"],
  },
 {
    id: "9",
    title: "Informatica",
    category: "Branding",
    categoryId: "branding",
    image: "/informatica.png?height=100&width=100",
    gallery: [
      "/informatica1.png?height=400&width=600",
      "/informatica2.png?height=100&width=100",
      "/informatica3.png?height=400&width=600",
      "/informatica4.png?height=400&width=600",
    ],
    expertise: ["Identidade visual", "Design de logotipo", "Materiais impressos", "Embalagens"],
    services: ["Logo Design", "Brand Identity", "Packaging", "Print Materials"],
    featured: true,
  },
  {
    id: "10",
    title: "Campanha de Jóias",
    category: "Design Gráfico",
    categoryId: "graphic-design",
    image: "/loja.svg?height=600&width=800",
    gallery: [
      "/loja2.svg?height=400&width=600",
      "/loja3.svg?height=400&width=600",
      "/loja4.svg?height=400&width=600",
      "/loja5.svg?height=400&width=600",
    ],
    expertise: ["Design para redes sociais", "Banners", "Templates de email", "Animação"],
    services: ["Social Media Graphics", "Banner Design", "Email Templates", "Animation"],
  },
  {
    id: "11",
    title: "Website para Restaurante",
    category: "Web Design",
    categoryId: "web-design",
    image: "/food3.png?height=600&width=800",
    gallery: [
      "/food.jpeg?height=400&width=600",
      "/food1.jpeg?height=400&width=600",
      "/food2.jpeg?height=400&width=600",
      "/food4.png?height=400&width=600",
    ],
    expertise: ["Design de interface", "Design responsivo", "Elementos interativos", "Arquitetura da informação"],
    services: ["Web Design", "Responsive Design", "Interactive Elements", "CMS Setup"],
  },
  {
    id: "12",
    title: "Marca de Moda",
    category: "Branding",
    categoryId: "branding",
    image: "/h3.svg?height=600&width=800",
    gallery: [
      "/h.svg?height=400&width=600",
      "/h1.svg?height=400&width=600",
      "/h2.svg?height=400&width=600",
      "/h3.svg?height=400&width=600",
    ],
    expertise: ["Identidade visual", "Design de logotipo", "Materiais impressos", "Embalagens"],
    services: ["Logo Design", "Brand Identity", "Packaging", "Print Materials"],

  },
]
